### ISSUE TITLE
Cannot stop Region Monitoring.

### ISSUE THREAD

**Issue by vscribner** [jbeuckm/TiBeacons#26]
First off I want to say thanks so much for your work on this module. We have been using it for some time and it has been fantastic. 

Second I have ran into an issue and would love to know if you have had any similar or heard of this happening. Recently I required the ability to stop monitoring for regions. 

I have followed the stopMonitoringForAllRegions(); from your example app but I simply get nothing. I don't get the info log and it does not stop monitoring. I am testing on iPhone6 with newest version.

Let me know if you can help at all, or what you need from me

**Comment by torlanco** [comment]
Any progress on this issue? I need to stop monitoring regions in an app that has dynamic regions.
